config/routes.rb
Gusto::Application.routes.draw do
  root to: "users#index"
  resources :pins, :only => [:new, :create, :index, :show, :destroy] do
    collection do
      post 'search'
    end
    member do
      get 'hourly'
      get 'daily'
    end
  end

  resources :users, :only => [:index, :new, :create, :edit, :update]

  resources :sessions, :only => [:new, :create, :destroy]

  match "/signup" => "users#new"
  match "/signin" => "sessions#new"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :name, :latitude, :longitude, :user_id

  belongs_to :user

  validates :latitude, presence: true
  validates :name, presence: true
  validates :longitude, presence: true
  validates :latitude, numericality:
    {less_than_or_equal_to: 90.0, greater_than_or_equal_to: -90.0 }
  validates :longitude, numericality:
    {less_than_or_equal_to: 180.0, greater_than_or_equal_to: -180.0 }
end

app/controllers/pins_controller.rb
require 'open-uri'
require 'json'
class PinsController < ApplicationController
  # GET /pins
  # GET /pins.json
  @@cache = { updated_at: Time.now }

  def search
    redirect_to action: "new", search: params[:search]
  end
  def index
    @@cache = {updated_at: Time.now} if !@@cache.has_key?(:updated_at) || Time.now.minus_with_coercion(@@cache[:updated_at]) > 2*60*60
    @new_pin = Pin.new
    @pins = []
    if session[:user_id]
      @pins = Pin.where("user_id = ?", session[:user_id]).sort_by(&:updated_at).reverse
      @pins.each do |pin|
        begin
          next if @@cache[pin]
          @@cache[pin] = {}
          open("http://api.wunderground.com/api/c86212bca3562794/conditions/q/#{pin.latitude},#{pin.longitude}.json") do |f|
            json_string = f.read
            parsed_json = JSON.parse(json_string)
            @@cache[pin][:location] = parsed_json['location']['city']
            @@cache[pin][:wind_mph] = parsed_json['current_observation']['wind_mph']
            @@cache[pin][:wind_dir] = parsed_json['current_observation']['wind_dir']
          end
          open("http://api.wunderground.com/api/c86212bca3562794/hourly/q/#{pin.latitude},#{pin.longitude}.json") do |f|
            json_string = f.read
            parsed_json = JSON.parse(json_string)
            @@cache[pin][:hourly] = parsed_json['hourly_forecast']
          end
          open("http://api.wunderground.com/api/c86212bca3562794/forecast10day/q/#{pin.latitude},#{pin.longitude}.json") do |f|
            json_string = f.read
            parsed_json = JSON.parse(json_string)
            @@cache[pin][:daily] = parsed_json['forecast']['simpleforecast']['forecastday']
          end
        rescue
          @pins.delete(pin)
        end
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])
    @pin.touch
    if !@@cache[@pin]
      pin = @pin
      @@cache[pin] = {}
      open("http://api.wunderground.com/api/c86212bca3562794/geolookup/conditions/q/#{pin.latitude},#{pin.longitude}.json") do |f|
        json_string = f.read
        parsed_json = JSON.parse(json_string)
        @@cache[pin][:location] = parsed_json['location']['city']
        @@cache[pin][:wind_mph] = parsed_json['current_observation']['wind_mph']
        @@cache[pin][:wind_dir] = parsed_json['current_observation']['wind_dir']
      end
      open("http://api.wunderground.com/api/c86212bca3562794/hourly/q/#{pin.latitude},#{pin.longitude}.json") do |f|
        json_string = f.read
        parsed_json = JSON.parse(json_string)
        @@cache[pin][:hourly] = parsed_json['hourly_forecast']
      end
      open("http://api.wunderground.com/api/c86212bca3562794/forecast10day/q/#{pin.latitude},#{pin.longitude}.json") do |f|
        json_string = f.read
        parsed_json = JSON.parse(json_string)
        @@cache[pin][:daily] = parsed_json['forecast']['simpleforecast']['forecastday']
      end
    end
    @location = @@cache[@pin][:location]
    @wind_mph = @@cache[@pin][:wind_mph]
    @wind_dir = @@cache[@pin][:wind_dir]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  def hourly
    @pin = Pin.find(params[:id])
    @location = @@cache[@pin][:location]
    @wind_mph = @@cache[@pin][:wind_mph]
    @wind_dir = @@cache[@pin][:wind_dir]
    @hourlies = @@cache[@pin][:hourly]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  def daily
    @pin = Pin.find(params[:id])
    @location = @@cache[@pin][:location]
    @wind_mph = @@cache[@pin][:wind_mph]
    @wind_dir = @@cache[@pin][:wind_dir]
    @days = @@cache[@pin][:daily]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    json_string = open("https://maps.googleapis.com/maps/api/place/textsearch/json?query=#{URI.escape(params["search"])}&sensor=false&key=AIzaSyAuc-paMz_ShQYipaLv-7hp7Lp5RCjIalI") { |f| f.read }
    @pin = Pin.new
    @results = JSON.parse(json_string)["results"].map do |elem|
      {
        name: elem["formatted_address"],
        latitude: elem["geometry"]["location"]["lat"],
        longitude: elem["geometry"]["location"]["lng"]
      }
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(params[:pin])
    if @pin.name.blank?
      @pin.name = "#{@pin.latitude}, #{@pin.longitude}"
      json_string = open("http://maps.googleapis.com/maps/api/geocode/json?latlng=#{@pin.latitude},#{@pin.longitude}&sensor=true") { |f| f.read }
      results = JSON.parse(json_string)["results"]
      if results.size > 0 && ! results[0]["formatted_address"].empty?
        @pin.name = results[0]["formatted_address"]
      end
    end

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>
      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: session[:user_id] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/_loc_form.html.erb
<%= form_for @new_pin, html: {id: "loc_form"} do |f|%>
  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>
  <%= f.hidden_field :user_id,   value: session[:user_id] %>
<% end %>

app/views/pins/_search_form.html.erb
<%= form_tag "/pins/search" do %>
  <input type="text" data-theme="b" name="search" id="search-basic" style="width: 100%;"/>
  <input style="float: right;" data-theme="b" value="Search" type="submit"/>
<% end %>

app/views/pins/daily.html.erb
<div data-role="header" data-theme="b">
  <%= link_to 'Home', pins_path, "data-icon" => "home" %>
  <h1><%= @pin.name %></h1>
</div>
<div data-role="content" data-theme="b">
  <h1 style="text-align: center" class="onimage"><%= @wind_mph %> mph <%= @wind_dir %></h1>
  <ul data-role="listview" data-inset="true">
    <% @days.each do |day| %>
      <% date = day["date"] %>
      <li><%= date["weekday_short"] %> <%= date["month"] %>/<%= date["day"] %>: <%= day["maxwind"]["mph"] %> mph <%= day["maxwind"]["dir"] %></li>
    <% end %>
  </ul>
</div>
<div data-role="footer" data-id="mainFooter" data-theme="b" data-position="fixed">
  <div data-role="navbar">
    <ul class="apple-navbar-ui comboSprite">
      <li><a href=<%= "/pins/#{@pin.id}" %>>Maps</a></li>
      <li><a href=<%= "/pins/#{@pin.id}/hourly" %>>Hourly</a></li>
      <li class="ui-btn-active ui-state-persist"><a href="#">Daily</a></li>
    </ul>
  </div>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/historical.html.erb
<div data-role="header">
  <%= link_to 'Home', pins_path, "data-icon" => "home" %>
  <h1><%= @location %></h1>
</div>
<div data-role="content">
    <h1 style="text-align: center"><%= @wind_mph %> mph <%= @wind_dir %></h1>
  <img style="display: block; margin-left: auto; margin-right: auto", src=<%="https://maps.googleapis.com/maps/api/staticmap?center=#{@pin.latitude},#{@pin.longitude}&zoom=11&size=300x250&sensor=false&key=AIzaSyADHdvKiue90VyVvgvgg37LJfkQMesWNWo"%>
</div>
<div data-role="footer" data-id="mainFooter" data-position="fixed">
  <div data-role="navbar" data-grid="c">
    <ul class="apple-navbar-ui comboSprite">
      <li><a href=<%= "/pins/#{@pin.id}" %>>Maps</a></li>
      <li><a href=<%= "/pins/#{@pin.id}/hourly" %>>Hourly</a></li>
      <li><a href=<%= "/pins/#{@pin.id}/daily" %>>Daily</a></li>
      <li><a href="#">History</a></li>
    </ul>
  </div>
</div>

app/views/pins/hourly.html.erb
<div data-role="header" data-theme="b">
  <%= link_to 'Home', pins_path, "data-icon" => "home" %>
  <h1><%= @pin.name %></h1>
</div>
<div data-role="content" data-theme="b">
  <h1 style="text-align: center" class="onimage"><%= @wind_mph %> mph <%= @wind_dir %></h1>
  <ul data-role="listview" data-inset="true">
    <% @hourlies.each do |hour| %>
      <li><%= hour["FCTTIME"]["civil"] %>: <%= hour["wspd"]["english"] %> mph <%= hour["wdir"]["dir"] %></li>
    <% end %>
  </ul>
</div>
<div data-role="footer" data-id="mainFooter" data-theme="b" data-position="fixed">
  <div data-role="navbar">
    <ul class="apple-navbar-ui comboSprite">
      <li><a href=<%= "/pins/#{@pin.id}" %>>Maps</a></li>
      <li class="ui-btn-active ui-state-persist"><a href="#">Hourly</a></li>
      <li><a href=<%= "/pins/#{@pin.id}/daily" %>>Daily</a></li>
    </ul>
  </div>
</div>

app/views/pins/index.html.erb
<div data-role="header" data-theme="b" id="page_header">
  <% if session[:user_id] %>
    <%= link_to "Sign Out", "/sessions/destroy", method: :delete %>
  <% else %>
    <%= link_to "Sign In", "/sessions/new" %>
  <% end %>
  <h1>My Locations</h1>
  <a id="userloc" class="crosshair" href="#" style="height:30px;"></a>
</div>

<div data-role="content" data-theme="b">
  <%= render "search_form" %>
  <%= render "loc_form" %>
  <h1 style="text-align: center;" class="onimage">History</h1>
  <% if @pins.empty? %>
    <% if session[:user_id] %>
      <p class="onimage">You don't have a history! Make your first search above or press the button in the top right to go to your current location.</p>
    <% else %>
      <p class="onimage"> You are not logged in, so we unfortunately cannot store your history. Please make an account or sign in!</p>
    <% end %>
  <% else %>
    <ul data-role="listview" data-inset="true" data-theme="b">
      <% @pins.each do |pin| %>
        <li><%= link_to pin.name, pin %></li>
      <% end %>
    </ul>
  <% end %>
</div>
<br/>

app/views/pins/new.html.erb
<div data-role="header" data-theme="b">
  <%= link_to 'Home', pins_path, "data-icon" => "home", "data-theme" => "b" %>
  <h1>New Pin</h1>
</div>

<div data-role="body">
  <%= render "search_form" %>
  <ul id="list" data-role="listview">
    <% @results.each do |result|%>
      <li>
        <a href="#" name="<%= result[:name] %>" latitude="<%= result[:latitude] %>" longitude="<%= result[:longitude]%>" onclick="new_pin_callback(this)">
          <%= result[:name] %>
        </a>
      </li>
    <% end %>
  </ul>
  <%= form_for @pin, html: { id: "myform" } do |f| %>
    <%= f.hidden_field :name, id: "nameinput" %>
    <%= f.hidden_field :latitude, id: "latinput" %>
    <%= f.hidden_field :longitude, id: "lnginput" %>
    <%= f.hidden_field :user_id, value: session[:user_id] %>
  <% end %>
</div>

app/views/pins/show.html.erb
<div data-role="header" data-theme="b">
  <%= link_to 'Home', pins_path, "data-icon" => "home" %>
  <h1><%= @pin.name %></h1>
</div>
<div data-role="content" data-theme="b">
  <h1 style="text-align: center" class="onimage"><%= @wind_mph %> mph <%= @wind_dir %></h1>
  <img style="display: block; margin-left: auto; margin-right: auto", src=<%="https://maps.googleapis.com/maps/api/staticmap?center=#{@pin.latitude},#{@pin.longitude}&zoom=13&size=300x250&sensor=false&key=AIzaSyAuc-paMz_ShQYipaLv-7hp7Lp5RCjIalI"%>
</div>
<div data-role="footer" data-id="mainFooter" data-position="fixed" data-theme="b">
  <div data-role="navbar">
    <ul class="apple-navbar-ui comboSprite">
      <li class="ui-btn-active ui-state-persist"><a href="#">Maps</a></li>
      <li><a href=<%= "/pins/#{@pin.id}/hourly" %>>Hourly</a></li>
      <li><a href=<%= "/pins/#{@pin.id}/daily" %>>Daily</a></li>
    </ul>
  </div>
</div>